//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CinemaManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Producer
    {
        public int Id { get; set; }
        public string name_ { get; set; }
        public string nationality { get; set; }
        public string email { get; set; }
    }
}
